### ISSUE TITLE
Impossible to open a company anymore

### ISSUE THREAD

**Issue by Nils85** [wuwanahq/wuwana2#147]
After merging the PR #144 it is not possible to open a company profile page.

Error in server logs:

```
PHP Fatal error:  Uncaught Error: Call to a member function bindValue() on boolean in /var/www/wuwana2/Models/DataAccess/Company.php:111
Stack trace:
#0 /var/www/wuwana2/Models/WebApp/Data.php(52): DataAccess\Company->selectPermalink('cafes-guayacan', 'EN')
#1 /var/www/wuwana2/router.php(65): WebApp\Data::getCompanyInfo('cafes-guayacan', 'en')
#2 {main}
  thrown in /var/www/wuwana2/Models/DataAccess/Company.php on line 111
```

SQL query:

```
select
			Company.Name as CompanyName,
			Company.LogoURL as CompanyLogoURL,
			Company.Description as CompanyDescription,
			Company.Website as CompanyWebsite,
			Company.Email as CompanyEmail,
			Company.Address as CompanyAddress,
			Location.RegionName as LocationRegionName,
			Province.$tagsLanguage as LocationProvince,
			Company.PhonePrefix as CompanyPhonePrefix,
			Company.PhoneNumber as CompanyPhoneNumber,
			Company.PostalCode as CompanyPostalCode,
			T1.Names as TagName1,
			T2.Names as TagName2,
			SocialMedia.URL as SocialMediaURL,
			SocialMedia.ProfileName as SocialMediaProfileName,
			SocialMedia.Biography as SocialMediaBiography,
			SocialMedia.ExternalLink as SocialMediaExternalLink,
			SocialMedia.Counter1 as SocialMediaCounter1,
			SocialMedia.Counter2 as SocialMediaCounter2,
			SocialMedia.Counter3 as SocialMediaCounter3,
			Image.URL as ImageURL,
			Company.LastUpdate as CompanyLastUpdate
from Company
			left join Province on Company.ProvinceID=Province.ProvinceID
			inner join SocialMedia on Company.ID=SocialMedia.CompanyID
			left join Image on SocialMedia.CompanyID=Image.CompanyID and SocialMedia.ID=Image.SocialMediaID
			left join Tag as T1 on Company.FirstTagID=T1.ID
			left join Tag as T2 on Company.SecondTagID=T2.ID
where Company.PermaLink=?
```

**Comment by Nils85** [comment]
**MySQL error**
`ERROR 1054 (42S22): Unknown column 'Location.RegionName' in 'field list'`
